[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# Testnet configurations
[rpc_endpoints]
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
anvil = "http://localhost:8545"

[etherscan]
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
